#!/bin/bash
. ./config
(grep-dctrl -e -F Depends,Build-Depends '('"$BUILD_DEPENDS"')' /var/lib/apt/lists/*_debian_dists_sid_main* -s Source; \
 grep-dctrl -e -F Depends,Build-Depends '('"$BUILD_DEPENDS"')' /var/lib/apt/lists/*_debian_dists_sid_main*Sources -s Package) \
 | awk '{print $2}' | sort -u
