#!/bin/bash
. ./config
BUILDLOG="$1"
PN=$(echo "$BUILDLOG" | sed -e 's|.*/||g; s|_amd64.*||g')
PKG=$(echo "$PN" | sed -e 's|_.*||g')
if [ -e "./build/${PKG}.hasbug" ]; then
  echo "Bug for package $PKG already exists."
  exit 1
fi
exec reportbug -P "User: $USER" -P "Usertags: $USERTAG" --source --no-query-source --no-debconf --no-query-bts --no-verify -I -b --from-buildd $PN --attach=$BUILDLOG
