#!/bin/bash
LISTFILE=list
if [ ! -z "$1" ]; then
  LISTFILE="$1"
fi

mkdir -p build
cd build
for i in $(cat "../${LISTFILE}"); do
  if [ ! -f ${i}.changes ]; then
    apt-get source -d -t unstable $i
    DEB_BUILD_OPTIONS=parallel=12 sbuild --no-run-lintian -d unstable $i*.dsc
    echo $? > ${i}.result
  fi
done

